# Generated by Django 2.1.5 on 2019-01-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Movie',
        ),
    ]
