# Generated by Django 2.1.5 on 2019-01-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190128_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='allocine_code',
            field=models.IntegerField(default='0', verbose_name='ID allocine'),
        ),
    ]
