# Generated by Django 2.1.5 on 2019-01-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('theater_code', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
    ]
