# Generated by Django 2.1.5 on 2019-01-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_theater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
    ]
