# Generated by Django 2.1.5 on 2019-03-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190302_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='id',
        ),
        migrations.AlterField(
            model_name='theater',
            name='theater_code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
