# Generated by Django 2.1.5 on 2019-03-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20190316_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='allocine_code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID allocine'),
        ),
    ]
