# Generated by Django 2.1.5 on 2019-03-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20190316_1027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showing',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='showing',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='showing',
            name='theater',
        ),
        migrations.DeleteModel(
            name='Showing',
        ),
    ]
